<?php

namespace niksnv\treeView;

use yii\base\Widget;


class TreeView extends Widget {

    private $test = 'test';

    public function run()
    {
        echo $this->test;
        parent::run(); // TODO: Change the autogenerated stub
    }

}